# Generated by Django 5.2 on 2025-04-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='user_report_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
