# Generated by Django 5.1.6 on 2025-03-15 17:42

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0002_alter_report_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reasons',
        ),
        migrations.DeleteModel(
            name='ClassificationReason',
        ),
        migrations.AddField(
            model_name='report',
            name='reasons',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('too_steep', 'Too steep'), ('lip_too_high', 'Lip too high'), ('cobbles', 'Cobblestones'), ('obstacle', 'Obstacle')], help_text='Select reasons (allowed only if classification is red or orange)', max_length=200, null=True),
        ),
    ]
