# Generated by Django 5.2 on 2025-04-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0002_report_user_report_number'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='report',
            name='mapper_repo_classif_843e11_idx',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='classification',
            new_name='condition',
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['condition'], name='mapper_repo_conditi_3576a8_idx'),
        ),
    ]
