# Generated by Django 5.2 on 2025-04-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0003_remove_report_mapper_repo_classif_843e11_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='condition',
            field=models.CharField(choices=[('none', 'None'), ('green', 'Green'), ('orange', 'Orange'), ('red', 'Red'), ('blue', 'Blue')], max_length=6),
        ),
    ]
