# Generated by Django 5.2 on 2025-04-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0004_alter_report_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_carer',
            field=models.BooleanField(default=False, verbose_name='Uses a wheeled mobility device'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobility_device_type_caree',
            field=models.CharField(blank=True, choices=[('manual_wheelchair', 'Manual Wheelchair'), ('powered_wheelchair', 'Powered Wheelchair'), ('mobility_scooter', 'Mobility Scooter'), ('tricycle', 'Tricycle'), ('adapted_bicycle', 'Adapted Bicycle'), ('bicycle', 'Bicycle'), ('other', 'Other')], max_length=50, null=True, verbose_name='Carees Mobility Device Type'),
        ),
    ]
