# Generated by Django 5.1.6 on 2025-03-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0004_alter_photo_options_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='classification',
            field=models.CharField(choices=[('green', 'Green'), ('orange', 'Orange'), ('red', 'Red'), ('blue', 'Blue')], max_length=6),
        ),
    ]
