# Generated by Django 5.2 on 2025-05-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0005_customuser_is_carer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='condition',
            field=models.CharField(choices=[('none', 'None'), ('green', 'Green'), ('orange', 'Orange'), ('red', 'Red'), ('white', 'White')], max_length=6),
        ),
    ]
