# Generated by Django 5.1.6 on 2025-03-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0006_alter_report_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='dropped_kerb_photos/'),
        ),
    ]
