# Generated by Django 5.2 on 2025-05-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0007_report_geocode_retry_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='geocode_retry_at',
        ),
    ]
