# Generated by Django 5.1.6 on 2025-03-29 17:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0007_alter_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
