# Generated by Django 5.2 on 2025-04-11 19:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0008_report_photo_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='reasons',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('steep_gradient', 'Steep gradient'), ('lip_too_high', 'Lip too high'), ('cobbles', 'Cobblestones'), ('obstacle', 'Obstacle'), ('no_visual_marking', 'No visual marking'), ('no_tactile_paving', 'No tactile paving'), ('narrow_pavement', 'Narrow pavement'), ('uneven_road_surface', 'Uneven road surface'), ('uneven_pavement_surface', 'Uneven pavement surface'), ('tight_turning_circle', 'Tight turning circle'), ('incorrectly_angled', 'Incorrectly angled'), ('broken_road_surface', 'Broken road surface'), ('broken_pavement_surface', 'Broken pavement surface'), ('accessibility_barrier', 'Accessibility barrier')], max_length=246, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapper.area'),
        ),
    ]
