# Generated by Django 5.2 on 2025-05-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0008_remove_report_geocode_retry_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localauthority',
            options={'verbose_name_plural': 'Local Authorities'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mobility_device_type_caree',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobility_device_type',
            field=models.CharField(blank=True, choices=[('manual_wheelchair', 'Manual Wheelchair'), ('powered_wheelchair', 'Powered Wheelchair'), ('manual_wheelchair_with_powered_front_attachment', 'Manual Wheelchair with Powered Front Attachment'), ('all_terrain_wheelchair', 'All Terrain Wheelchair'), ('mobility_scooter', 'Mobility Scooter'), ('tricycle', 'Tricycle'), ('handcycle', 'Handcycle'), ('adapted_bicycle', 'Adapted Bicycle'), ('bicycle', 'Bicycle'), ('other', 'Other')], max_length=50, null=True, verbose_name='Mobility Device Type'),
        ),
    ]
