# Generated by Django 5.2 on 2025-04-11 21:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0009_area_alter_report_reasons_report_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
