# Generated by Django 5.2 on 2025-04-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0012_localauthority_parish_alter_county_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='parish',
        ),
        migrations.AddField(
            model_name='report',
            name='place_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Parish',
        ),
    ]
