# Generated by Django 5.2 on 2025-04-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0013_remove_report_parish_report_place_name_delete_parish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localauthority',
            old_name='county',
            new_name='local_authority',
        ),
    ]
