# Generated by Django 5.2 on 2025-04-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0014_rename_county_localauthority_local_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='road_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
