name: Build and Deploy to Azure Container App

on:
  push:
    branches: [ "azure-dev" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: azure-dev

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: droppedkerbmapper-f6cse9c6dzebewhj.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: docker build -t droppedkerbmapper-f6cse9c6dzebewhj.azurecr.io/droppedkerbmapper:latest .

      - name: Push Docker image
        run: docker push droppedkerbmapper-f6cse9c6dzebewhj.azurecr.io/droppedkerbmapper:latest

      - name: Install Azure Container Apps CLI extension
        run: az extension add --name containerapp --upgrade

      - name: Deploy Azure Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: mobility-mapper-rg
          containerAppName: droppedkerbmapper-app
          imageToDeploy: droppedkerbmapper-f6cse9c6dzebewhj.azurecr.io/droppedkerbmapper:latest
          registryUrl: droppedkerbmapper-f6cse9c6dzebewhj.azurecr.io
          registryUsername: ${{ secrets.ACR_USERNAME }}
          registryPassword: ${{ secrets.ACR_PASSWORD }}
